// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9klScyAgpN-rd2QqTNDKJh_6f-4Z5Vn0',
    appId: '1:843006606880:android:c7556d45dde367fcde0645',
    messagingSenderId: '843006606880',
    projectId: 'kickbasekumpel',
    storageBucket: 'kickbasekumpel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Uzkkn38uyeBk79GQtO0RJbztZRzWQuc',
    appId: '1:843006606880:ios:ace0cffa4a7c702ede0645',
    messagingSenderId: '843006606880',
    projectId: 'kickbasekumpel',
    storageBucket: 'kickbasekumpel.firebasestorage.app',
    iosBundleId: 'de.legomaniac.kickbasekumpel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Uzkkn38uyeBk79GQtO0RJbztZRzWQuc',
    appId: '1:843006606880:ios:ace0cffa4a7c702ede0645',
    messagingSenderId: '843006606880',
    projectId: 'kickbasekumpel',
    storageBucket: 'kickbasekumpel.firebasestorage.app',
    iosBundleId: 'de.legomaniac.kickbasekumpel',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwu1rs5Dvr_L0iMnv_6hdbBHWCvwokrxs',
    appId: '1:843006606880:web:873da22f6bdea565de0645',
    messagingSenderId: '843006606880',
    projectId: 'kickbasekumpel',
    authDomain: 'kickbasekumpel.firebaseapp.com',
    storageBucket: 'kickbasekumpel.firebasestorage.app',
    measurementId: 'G-F107DFZ643',
  );
}
